package tests;

/*Generated by MPS */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({BlubTest.class, tests.Suite.class})
public class AllSuite {
}
