package tests;

/*Generated by MPS */

import org.junit.Test;
import package2.Blub;
import org.junit.Assert;

public class BlubTest {


  @Test
  public void testBlubArray() {
    Blub blub = new Blub();
    int[] array = new int[]{1};
    double[] doubleArray = new double[]{1.1};
    int[] result_a0a = blub.blubArray();
    Assert.assertArrayEquals("isEqual with arrays", array, result_a0a);
    double[] result_b0a_0 = blub.blubArrayDouble();
    Assert.assertArrayEquals("Delta for double arrays", doubleArray, result_b0a_0, 1.5);
    double result_c0a = blub.blubDouble();
    Assert.assertNotEquals("isNotEqual with double", 2, result_c0a, 1);
    Blub result_d0a_0 = blub.blubBlub();
    Assert.assertNotNull(result_d0a_0);
    Object result_e0a = blub.blubObject();
    Assert.assertNull(result_e0a);
  }
  @Test
  public void testBlubBlub() {
    Assert.fail("Not yet implemented");
  }
}
