package tests;

/*Generated by MPS */

import org.junit.runner.RunWith;

@RunWith(org.junit.runners.Suite.class)
@org.junit.runners.Suite.SuiteClasses({Test.class, StackTest.class})
public class Suite {
}
